### ISSUE TITLE
Error By Choosing Payload

### ISSUE THREAD

**Issue by MBrants** [000Zer000/ZKit-Framework#12] opened 2020-08-20 11:46 UTC
Here is the error code,
```

..> 2

{1} --> python_ransomware_tcp >>> lib/payloads/ransomware/python_ransomware_tcp

{2} --> python_ransomware_udp >>> lib/payloads/ransomware/python_ransomware_udp                                                                                       

{000} --> Back To Main Menu
Please Choose One Of Them (Number Of It): 1
Sth went really wrong that we couldnt handle it
the exceptions value have saved to Errors.log
please report this on github to me.Do you want zkit to reraise it ? (reraising may help better) (Y/N): Y
This is going to print full error . please report it on github
Traceback (most recent call last):
  File "zkit.py", line 115, in <module>
    crash_handler(e)
  File "zkit.py", line 111, in <module>
    starter.main_loop()
  File "zkit.py", line 104, in main_loop
    self.execute(choice)
  File "zkit.py", line 84, in execute
    self._execute_payload_related(choice)
  File "zkit.py", line 80, in _execute_payload_related
    list_builtin_payloads_helper(choice)
  File "zkit.py", line 38, in list_builtin_payloads_helper
    Generate(list(payloads.values())[int(index) - 1])
  File "/home/server/Desktop/ZKit-Framework-master/ui_core/_core.py", line 66, in __init__
    self.pg = PayloadGenerator(self.root)
  File "/home/server/Desktop/ZKit-Framework-master/lib/payload.py", line 98, in __init__
    AntiMalware(self.root + payload + ".py")
  File "/home/server/Desktop/ZKit-Framework-master/lib/payload.py", line 32, in __init__
    self.fd = self._remove_comments(fd)
NameError: name 'fd' is not defined
```

**Comment by 000Zer000** [comment] 2020-08-20 11:49
OK let me see this 

Have Fun !

**Comment by MBrants** [comment] 2020-08-20 11:51
> OK let me see this
> 
> Have Fun !

Okay thx, i hope i can run this program soon

**Comment by 000Zer000** [comment] 2020-08-20 11:52
Now i have commited a fix for this error . please check if its fixed or not

**Comment by MBrants** [comment] 2020-08-20 11:53
I will check it , please give me 5min

**Comment by 000Zer000** [comment] 2020-08-20 11:53
> I will check it , please give me 5min

OK

**Comment by MBrants** [comment] 2020-08-20 11:54
ERROR CODE,
```
..> 2

{1} --> python_ransomware_tcp >>> lib/payloads/ransomware/python_ransomware_tcp

{2} --> python_ransomware_udp >>> lib/payloads/ransomware/python_ransomware_udp

{000} --> Back To Main Menu
Please Choose One Of Them (Number Of It): 1
Sth went really wrong that we couldnt handle it
the exceptions value have saved to Errors.log                                                                                                                         
please report this on github to me.Do you want zkit to reraise it ? (reraising may help better) (Y/N): y
This is going to print full error . please report it on github
Traceback (most recent call last):
  File "zkit.py", line 115, in <module>
    crash_handler(e)
  File "zkit.py", line 111, in <module>
    starter.main_loop()
  File "zkit.py", line 104, in main_loop
    self.execute(choice)
  File "zkit.py", line 84, in execute
    self._execute_payload_related(choice)
  File "zkit.py", line 80, in _execute_payload_related
    list_builtin_payloads_helper(choice)
  File "zkit.py", line 38, in list_builtin_payloads_helper
    Generate(list(payloads.values())[int(index) - 1])
  File "/home/server/Desktop/ZKit-Framework-master/ui_core/_core.py", line 66, in __init__
    self.pg = PayloadGenerator(self.root)
  File "/home/server/Desktop/ZKit-Framework-master/lib/payload.py", line 98, in __init__
    AntiMalware(self.root + payload + ".py")
  File "/home/server/Desktop/ZKit-Framework-master/lib/payload.py", line 33, in __init__
    self.check_for_threats()
TypeError: check_for_threats() missing 1 required positional argument: 'file'
```

**Comment by 000Zer000** [comment] 2020-08-20 11:55
Oh men This release is full of bugs . could you give me a sec checking everything ?

**Comment by MBrants** [comment] 2020-08-20 11:56
Of course take your time, let me know if you released a new fix

**Comment by 000Zer000** [comment] 2020-08-20 11:56
It looks like im going to release several fixes :) 

Have Fun !

**Comment by MBrants** [comment] 2020-08-20 11:57
Alright, great to hear :)

**Comment by 000Zer000** [comment] 2020-08-20 12:16
Now, i have commited several fixes but linked only one of them . and about the ransomware . it shredds itself after encrypting everything . and deletes itself after it . and please compile it using `--uac-admin` flag if on windows . windows payloads have to be compiled but not about linux ones . if you encountered any problems just let me know .

**Comment by 000Zer000** [comment] 2020-08-20 12:20
I hope you understand me . im now in middle of shit . im moving from windows to linux . im transfering all my data , passwords, everything . but it doesnt mean i wont answer . it means the development may be a little slower . 

Anyway Have Fun !

**Comment by MBrants** [comment] 2020-08-20 13:54
Alright i will check it right now

**Comment by 000Zer000** [comment] 2020-08-20 14:06
> Alright i will check it right now

After you have used it . can you email me please ??

**Comment by 000Zer000** [comment] 2020-08-21 08:51
It looks like the issue is fixed . Im closing it . If any problem occured please reopen it or submit another issue

**Closed by 000Zer000** 2020-08-21 08:51 UTC
Labels: Bug
